name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.7.1
    - uses: actions/checkout@v3
    - name: Setup riscv gnu/gcc toolchain
      uses: ChnMasterOG/setup-riscv-gnu-toolchain@v5.0
      with:
        version: 91402143
    - run: riscv-none-elf-gcc --version
    - name: make
      run: |
            cd ./mounriver_project
            python replace_path.py
            echo "build KEYBOARD_CH582M..."
            cd ./KEYBOARD_CH582M/obj
            make
            echo "build RF_CH582M..."
            cd ../../
            cd ./RF_CH582M/obj
            make
            echo "build VLD_CH582M..."
            cd ../../
            cd ./VLD_CH582M/obj
            make
